### ISSUE TITLE
Not an issue...per se

### ISSUE THREAD

**Issue by SpartanGeek2014** [learn-co-curriculum/orm-video-review-codealong-building-a-room-scraper-and-orm#10]
I feel the video's placement in the curriculum is perfectly timed. It was not that far back that we were building "scraper" apps, so incorporating them into the ORM/SQL lessons as a way to show how all this can be and is actually combined in the 'real world' of programming was great.  I like seeing these lessons put to work and knowing how the skills I'm learning can be creatively put to use.

**Comment by curiositypaths** [comment]
Hi there,

We are super glad the placement of this video worked well for you.
