### ISSUE TITLE
Suggested Summary and Objective

### ISSUE THREAD

**Issue by JDSweeney1** [learn-co-curriculum/orm-video-review-codealong-building-a-room-scraper-and-orm#11]
SUMMARY
   In this video, Avi covers both scraping and ORM, including dynamic-ORM. He starts off showing how to set up a project's environment and set up. He then goes on and quickly demonstrates methods and tactics used to scrape websites for information. He then continues on to developing ORM using SQLITE3. Using queries, he was able to instantiate a new table and insert massive amounts of data about room-mates. He then went on and refactored/refined(reification), his objects so they would not be class specific, but rather available for all classes that inherited from this parent class. He also used the example of chess masters and how they remember not specific board setups, but rather the pattern for which they came about.  Also, the guy who created ActiveRecord made a mistake with the library name(active_record). Noticing it too late, it could not be changed. 

OBJECTIVES

- Learn how to set up an environment.

- Use notes to develop an outline of what to do and what will be accomplished.

- Use the scraper method to help build a database.

- Insert the data into an SQLITE3 database.

- Be able to retrieve that information and reinstantiate it into a ruby object.

- Use queries to return the desired data.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your Suggested Summary and Objectives.
