### ISSUE TITLE
Suggested Summary.

### ISSUE THREAD

**Issue by Ssenkowski** [learn-co-curriculum/orm-video-review-codealong-building-a-room-scraper-and-orm#12]
"CODE ALONG, BUILDING A ROOM SCRAPER AND ORM - OVERVIEW" explains what's involved to build a scraper that utilizes Object Relational Mapping (ORM).  Avi walks new programmers through the initial thought process of outlining a program's structure, developing it using Ruby, SQL and Object Relational Mapping and briefly introduces the database toolkit for Ruby, ActiveRecord.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your Suggested Summary.
