### ISSUE TITLE
Video cuts off abruptly in mid-sentence

### ISSUE THREAD

**Issue by wlycdgr** [learn-co-curriculum/orm-video-review-codealong-building-a-room-scraper-and-orm#13]
Avi is starting to wrap up when the video cuts off, but it seems like at least a few minutes are missing from the end of the video.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#17.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
