### ISSUE TITLE
Suggested summary and objectives

### ISSUE THREAD

**Issue by thurman024** [learn-co-curriculum/orm-video-review-codealong-building-a-room-scraper-and-orm#15]
Summary:
This video demonstrates modeling a web scraper to instantiate objects and persist the equivalent data in a database table.  This process reviews previously covered concepts regarding Nokogiri scraping, Ruby classes, and SQLite database tables

Objectives:
Create Ruby classes and objects that model the real world data you are handling.
Persist your data into a SQLite database table using ORM principles.
Introduce ActiveRecord as built-in, abstract ORM functionality.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your Suggested Summary and Objectives.
