### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by MERCERNYC** [learn-co-curriculum/orm-video-review-codealong-building-a-room-scraper-and-orm#16]
**SUMMARY**

First part of this video, will show how to create a CLI scraper and how to set up environment and console by applying the task: method that provide a nice way to handle common tasks surrounding a ruby project.  Second part of this video, will introduce a powerful gem called Active Record and how this gem can save you time by communicating between your  Ruby program and your database with less code.

**Objectives** 

- Build scrapping method that use data to instantiate new objects
- Integrate the database with scrapping object and reifying those methods
- Understand the method Tap to have a  block return the object itself
- Query SQL to sort database instead of ruby code 
- Implement Active Record and how it can be a useful gem

**OTHER WAYS TO TO HELP IMPROVE THESE VIDEOS**

This video have a great content of scrapping and SQL. The first part of the video would be great if presented before the CLI project.  The second part, I believe is in the right order, before Active Record material is covered giving student a basic understanding of this powerful gem. Fast pace but great lecture by Avi.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your Suggested Summary and Objectives.
