### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by kpiipari** [learn-co-curriculum/orm-video-review-codealong-building-a-room-scraper-and-orm#2]
**Summary**

This video shows you how to build a website Scraper (scraping Craigslist roommates), how to create Ruby objects from the scraped details and how to persist the instances to a SQLite database.

**Objectives**

- Scrape a website, instantiate objects and persist to a database

**Comment by gj** [comment]
Looks good @kpiipari ! [Edit the lesson](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), and I'll have a look at the changes. Thanks!

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your Suggested Summary and Objectives.
