### ISSUE TITLE
Recording ends abruplty...

### ISSUE THREAD

**Issue by skmcloughlin** [learn-co-curriculum/orm-video-review-codealong-building-a-room-scraper-and-orm#3]
Not a huge issue, as Avi was almost done, but is something that could be edited out.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#17.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
