### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by kyleblee** [learn-co-curriculum/orm-video-review-codealong-building-a-room-scraper-and-orm#5]
_Suggested Summary_
In this lesson, we’ll revisit the steps involved with setting up a new project structure before reviewing the common patterns that are used in an ORM (and how to build those methods manually). We will do this by creating a CLI application that helps a user search for a new roommate. The application will be responsible for scraping data from Craigslist room listings, turning that data into Ruby objects, and saving / accessing the data from a SQLite3 database. We’ll wrap up by explaining how all of these ORM topics are essential for understanding our next unit: _ActiveRecord_. 

_Suggested Objectives_
- Correctly setup a new project structure with the proper directories and files (including an environment file and a console)
- Understand “implementation mode” vs. “design mode” and why you should switch between the two when programming (not trying to do both at the same time)
- Explain how the _or / else operator_ works and how it can be used in a program
- Use Nokogiri (along with trial and error) to effectively scrape data from a webpage, like Craigslist, and return that data as a hash
- Use a hash of scraped data to instantiate new objects of a given class
- Understand that _.create_ is frequently a combination of two separate, independent behaviors: instantiating a new object and saving that object’s data to the database
- Define a database connection in the environment.rb file—using a constant—for easy reference throughout your program
- Turn a row (or rows) of data returned by a database into a Ruby object (or Ruby objects)
- Use _#tap_ to take advantage of block-level variables, extend an instance’s instantiation with additional behavior, and automatically return an instance object that was just created
- Use the right tool for the job when it comes to sorting data (SQL), instead of relying solely on Ruby
- Understand that ActiveRecord is a collection (or library) of all the ORM methods that we have been learning to build—and many, many more—which can be inherited into a class

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your Suggested Summary and Objectives.
