### ISSUE TITLE
Definitions 

### ISSUE THREAD

**Issue by Sidhe-is-me** [learn-co-curriculum/orm-video-review-codealong-building-a-room-scraper-and-orm#6]
At  timestamp 1:05:22 Avi misuses reify.
I think it would be helpful to add the definitions of abstraction and reify in the lesson plan.

Reify
transitive verb
:to consider or represent (something abstract) as a material or **concrete thing** :to give definite content and form to (a concept or idea)

[Definiton](https://www.merriam-webster.com/dictionary/reify)

Abstract

adjective
adjective: abstract
abˈstrakt,ˈabˌstrakt/Submit
1.existing in thought or as an idea but **not having a physical or concrete existence.**

[ Definition](https://www.google.com/search?q=abstract&oq=abstract&aqs=chrome..69i57j69i60j0j69i60l2j0.2143j0j4&sourceid=chrome&ie=UTF-8)

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#17.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
