### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by christian-egglin** [learn-co-curriculum/orm-video-review-codealong-building-a-room-scraper-and-orm#7]
Summary suggestion: This video covers the process of instantiating Ruby objects using information scraped from a website using a room/roommate domain model. It then describes the ways to persist the Ruby object data into a database and connect this database to the Ruby class using an ORM pattern. Finally, it talks about how this ORM pattern is a simplified version of what is done by the ActiveRecord Ruby Gem.

Objective suggestion: Insert data into a table that is scraped from a website

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your Suggested Summary and Objectives.
