### ISSUE TITLE
Suggested Summary

### ISSUE THREAD

**Issue by hdanziger** [learn-co-curriculum/orm-video-review-codealong-building-a-room-scraper-and-orm#8]
this video creates a database of all the available rooms in new york, chicago, and london that can then be organized as the user sees fit. 
The scraping allows for the programmer to get information directly from the site for the database without having to copy out individual entries. 
ORM allows the user to organize databases easily and sort through and identify individual instances of a class and its corresponding information. 
we use both ruby and SQL here to create our methods for our database and organize our data.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your Suggested Summary.
