### ISSUE TITLE
Suggested Summary

### ISSUE THREAD

**Issue by allisonkadel** [learn-co-curriculum/orm-video-review-codealong-building-a-room-scraper-and-orm#9]
Learn to create ruby methods that scrape data from a website, instantiate objects with that data, persist the data to a database, and query that data using SQL. Then learn how to utilize the Ruby gem Active Record to implement all of those methods for you!

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your Suggested Summary.
